services:
  - type: web
    name: stream-extractor-proxy
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PROXY_SERVER
        value: ""
      - key: PROXY_USERNAME
        value: ""
      - key: PROXY_PASSWORD
        value: ""
